services:
  - type: web
    name: nexus-code-backend
    env: node
    rootDir: backend
    buildCommand: "apt-get update && apt-get install -y gcc python3 && npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: "5000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
